### ISSUE TITLE
feature/set provider user location on login

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#100]
**Tell us about your request!**
To improve the accuracy of location based reporting, we'll need to ask users to set their location on login

**Which app does this concern?**
Provider portal

**What will be benefit of this feature?**
We will improve the accuracy of location reporting and KPIs which will help providers understanding their performance across their sites

**Describe the solution you'd like**
Once a user logs in, display a modal asking them to set their location
![image](https://user-images.githubusercontent.com/18426797/154550236-36c37e54-1162-4d6b-a91f-59ae5d60da09.png)

It could be helpful to let them set their practitioner profile as well i.e. if the practitioners has more than one profile

**Describe alternatives you've considered**
We're currently inferring location based on doctor slots which isn't that accurate

**Additional context**
N/A

**Comment by seddie62** [comment]
@dexios1 would this be every time they log in? Even with token expiry and all?

**Comment by chris-dare** [comment]
@seddie62, yes so we will need to extend the lifetime of the token.

**Comment by chris-dare** [comment]
Here is feedback following your merge request: https://www.loom.com/share/d49ee29b8fc84f269de6878bacbd46c6

**Comment by chris-dare** [comment]
Comments post review:
This is great!!!
I see that it works if the user explicitly clicks the logout button and logs in again.

Only 2 things to be updated:
1. Extending the lifetime of the access and refresh tokens
2. Ensuring that this feature works for login when the token expires
