### ISSUE TITLE
bugfix/fetching previous encounters for a patient

### ISSUE THREAD

**Issue by TuyizereBapt** [serenity-health/roadmap#102]
**Describe the bug**
Doctors cannot see previous encounters for a patient

**Impact**
Doctors cannot see previous notes about a patient to inspire what to do next

**To Reproduce**
...

**Expected behavior**
...

**Additional context**
N/A

**Comment by chris-dare** [comment]
Hey @TuyizereBapt I fixed this in https://github.com/serenity-health/core-systems-api/pull/41
