### ISSUE TITLE
feature/set payer on raising pharmacy bill

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#109]
**Tell us about your request!**
Should be possible to raise bill for a pharmacy item and set the payer if the payment method and account is set. If not present and payment is being received (`with_payment=True`) then this should fail unless it's for a cash payment

**Which app does this concern?**
Provider portal

**What will be benefit of this feature?**
Providers can generate accurate claims for submission to payers

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chris-dare** [comment]
Hi @pkdadson,

Please let me know if the frontend change is up

**Comment by pkdadson** [comment]
> Hi @pkdadson,
> 
> Please let me know if the frontend change is up

the frontend was up since last week

**Comment by chris-dare** [comment]
> > Hi @pkdadson,
> > Please let me know if the frontend change is up
> 
> the frontend was up since last week

Ok thank you. Please notify via comments going forward so that there's some awareness. It helps so the status/progress is clear and next actions can be taken @pkdadson

**Comment by chris-dare** [comment]
Hi @pkdadson please check out the dispense checkout again. 

Here is some context behind the errors users may encounter: https://www.loom.com/share/e77ce386634743419cf515d1d6d09c99

**Comment by chris-dare** [comment]
> Hi @pkdadson please check out the dispense checkout again.
> 
> Here is some context behind the errors users may encounter: https://www.loom.com/share/e77ce386634743419cf515d1d6d09c99

This probably deserves a card on it's own.
