### ISSUE TITLE
bugfix/change service request status to active

### ISSUE THREAD

**Issue by TuyizereBapt** [serenity-health/roadmap#114]
**Describe the bug**
After a ServiceRequest is paid for, the status stays as draft rather than active

**Impact**
What is the impact of this problem?

**Expected behavior**
After payment for ServiceRequest, the status of the ServiceRequest should be set to ACTIVE

**Screenshots/Screencast**

**Additional context**
`diagnostics.models.ServiceRequest.process_payment(...)`

**Comment by chris-dare** [comment]
Thank you @TuyizereBapt

**Comment by chris-dare** [comment]
Just an FYI: I took the screenshots from the issue description because they contained PII from production
