### ISSUE TITLE
feature/update bill cancelations

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#121]
**Tell us about your request!**
Update the bill cancelation feature on Serenity such that authorized practitioners (AP's) can request cancelations which can be approved and finally marked as cancelled upon reversal of payments. 

See the [Serenity EMR - Bill cancelations flowchart](https://github.com/serenity-health/roadmap/files/8318187/Serenity.EMR.-.Bill.cancelations.pdf) to learn more about the bill cancelation procedure. A screenshot of that flow is listed below. The original copy is available [here](https://github.com/serenity-health/roadmap/files/8314442/Serenity.EMR.-.Bill.cancelations.pdf)

![Serenity EMR - Bill cancelations](https://user-images.githubusercontent.com/18426797/159237516-84fe8531-46e5-4f65-b8d2-bc5dc22caf1e.jpg)

Here's what we should be able to accomplish following this improvement:

*In scope*
1. APs can request a bill cancelation
2. APs can approve a bill cancelation
3. APs can cancel a cancelation for a debit bill after they have manually determined a successful refund
4. Cash/debit payments will be cleared for cancelation post approval iff payment has been refunded to the payer(s) and credit payments will be automatically reversed
5. If stock items like drugs were given to patients as part of the benefits of bill payment, the application should automatically update the inventory to reflect the expected return of those drugs
6. If a service was to be delivered as a benefit of the bill payment and has not yet been done, then that encounter/service delivery should automatically be canceled as well

*Out of scope*
1. APs will be automaticall notified in app when a cancelation event occurs. Cancelation events may include request, approval or cancelation of a bill
2. APs can reject a cancelation
3. Automated/digitized processing of chargebacks

**Which app does this concern?**
Provider portal? Corporate portal? Patient app?

**What will be benefit of this feature?**
What's the value of this feature? If you can quantity it, that would be awesome!

**Describe the solution you'd like**
We're going to implement the flow in the description above with the exception its notification feature

Here's what should be updated in the app:
1. Add a field for mode of payment on the following models: PatientAccount, ClientAccount, ChargeItem
4. The options for the mode of payment will be `CREDIT`, or `DEBIT`
7. When creating a patient account, the default will be `DEBIT` and the for ClientAccount, this will be `CREDIT`
8. When paying for a charge item, if a client account is used to make the payment, then we will set the charge_item's mode of payment to client_account.payment_mode
9. Otherwise, we will set the mode of payment to patient_account.payment_mode
10. Now, if the mode of payment is debit, the we will debit the account balance for both patient and client account
11. However, if the mode of payment is credit, we will debit the account limit instead and proceed to raise a claim
12. Now, in `ChargeItemCancelation.cancel`, if the chargeitem has stock items (i.e. stock items were dispensed for the bill) then we will update the stock and record its adjustment
13. Finally, in the `ChargeItemCancelation.approve`, if the chargeitem was paid in credit mode, then we will automatically call `ChargeItemCancelation.cancel` within the model as well
Note: Be sure to check and confirm that `ChargeItemCancelation.cancel` does not raise bugs. Some of that activity has been spotted in the app

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chris-dare** [comment]
Hey @TuyizereBapt, you'll need to implement a method on Stock like `Stock.pop()`

It will help us encapsulate the behaviour of topping up the inventory through ops like cancelations/refunds

So I'm thinking something 

```python
def push(self, quantity_to_add: int, actor: User) -> (Stock, InventoryActionHistory)
```

Then you can call this in ChargeItemCancelation to update inventory on bill cancelation

**Comment by TuyizereBapt** [comment]
> 4. When paying for a charge item, if a client account is used to make the payment, then we will set the charge_item's mode of payment to client_account.payment_mode
> 5. Otherwise, we will set the mode of payment to patient_account.payment_mode

Which method on **ChargeItem** as shown in the snapshot below is used to pay for a ChargeItem? both? 
ChargeItem.settle_payment() is somehow confusing

![image](https://user-images.githubusercontent.com/37751827/159335437-c851ab19-45d9-466d-ad7a-8f91e886d1fb.png)

**Comment by chris-dare** [comment]
> 

Use `settle_payment`

Please run a safe delete on `settle_payment_with_corporate` and take it out if it's not used anywhere. We don't use it anymore

**Comment by TuyizereBapt** [comment]
> > 
> 
> Use `settle_payment`
> 
> Please run a safe delete on `settle_payment_with_corporate` and take it out if it's not used anywhere. We don't use it anymore

So how do I know which type of account is used to pay for the ChargeItem? From the info in screshots below

Is it PaymentInfoPydanticModel.account_id or PaymentInfoPydanticModel.account? Os something else?

Why multiple charge_items by `charge_items = process_payment_via_account(...)`?

![image](https://user-images.githubusercontent.com/37751827/159336609-58e9234e-55c2-44bc-a84e-f3c0b7e9d70a.png)

![image](https://user-images.githubusercontent.com/37751827/159336708-3fc3967e-843a-4d3a-9a9a-6812c80f7383.png)

**Comment by chris-dare** [comment]
Under settle_payment, The charge item in 

```python
charge_item = charge_items[0]
```

Will have either a patient_account, a payer_account or both.

It there is a `charge_item.patient_account`, set the mode to `patient_account.payment_mode`
Otherwise, set it to `charge_item.payer_account.payment_mode`

**Comment by TuyizereBapt** [comment]
> Under settle_payment, The charge item in 
> 
> ```python
> charge_item = charge_items[0]
> ```
> 
> Will have either a patient_account, a payer_account or both.
> 
> It there is a `charge_item.patient_account`, set the mode to `patient_account.payment_mode`
> Otherwise, set it to `charge_item.payer_account.payment_mode`

Okay. Thanks

**Comment by chris-dare** [comment]
You're welcome. I just updated the comment FYI

**Comment by TuyizereBapt** [comment]
> > 
> 
> Use `settle_payment`
> 
> Please run a safe delete on `settle_payment_with_corporate` and take it out if it's not used anywhere. We don't use it anymore

It looks like `settle_payment_with_corporate` is used somewhere

![image](https://user-images.githubusercontent.com/37751827/159339772-7c348744-d3ba-47fe-826f-ce98f8a31d44.png)

**Comment by chris-dare** [comment]
ok. just raise a NotImplementedError in `settle_payment_with_corporate` with todo to delete
Alternatively, you can delete that ..WithdrawalListView. It's useless

**Comment by TuyizereBapt** [comment]
Let me delete both the View where it's used and the method itself

**Comment by chris-dare** [comment]
Sure

**Comment by TuyizereBapt** [comment]
That `ChargeItem.stock_item` Isn't the reference of the foreignkey wrong? I think it should have been Stock rather ChargeItem

How can I know the stock associated with the ChargeItem?

![image](https://user-images.githubusercontent.com/37751827/159459248-a6443674-fca4-4cc4-9354-5448816fc12d.png)

**Comment by chris-dare** [comment]
That's correct. Change it

**Comment by chris-dare** [comment]
See `medication.models.MedicationDispense.create`,

Particularly in 355 that says `# create charge item for that dispense and add to the invoice`

**Comment by TuyizereBapt** [comment]
> See `medication.models.MedicationDispense.create`,
> 
> Particularly in 355 that says `# create charge item for that dispense and add to the invoice`

What does this mean?

**Comment by chris-dare** [comment]
This is where you can can set the stock on the charge item being created

**Comment by TuyizereBapt** [comment]
> That's correct. Change it

Is this not going to break things?

**Comment by chris-dare** [comment]
Depends. What would you like to do?

**Comment by TuyizereBapt** [comment]
> This is where you can can set the stock on the charge item being created

`inventory_item` is Stock right?

**Comment by chris-dare** [comment]
That's correct. Let's have a chat on this. Please come to Gather

**Comment by chris-dare** [comment]
Concerning revoking a service request, there are 3 things that are necessary:

1. Setting the status of the service request to revoked. Where this means _"the request (and any implicit authorization to act) has been terminated prior to the known full completion of the intended actions. No further activity should occur"_
2. Setting actor of the revoke action: i.e a foreign key to the practioner role and then also the name of the actor who revoked the request  
Please create these fields on the `ServiceRequest` called:
a. `canceled_by_practitioner` -> FK to the `Practitionerrole` where the practitionerrole must have the same managing organization as `ServiceRequest.healthcareservice.provider`.  
i.e If I should only be able to cancel a service request at Hospital A iff I work there.
b. `canceled_by_user`  -> FK to `authenticationmanager.User`
c. `canceled_by_name` -> Text of the fullname of the canceled_by_practitioner if not null else canceled_by_user

We need `canceled_by_user` because when the patient portal comes online, users may have the ability to cancel diagnostic service request which they are yet to pay for.

3. Setting the time the cancelation occured

**Comment by chris-dare** [comment]
Hi @pkdadson, I noticed that samples can be taken for a test when it's revoked. Please update this so the samples are only taken if the status is `active`. Because that's the only stage where a sample is expected to be collected to continue the process.

![image](https://user-images.githubusercontent.com/18426797/159513603-eaa9c271-7cd0-4416-99b4-b27d1f08a8bf.png)

**Comment by pkdadson** [comment]
<img width="1437" alt="Screenshot 2022-03-28 at 00 52 32" src="https://user-images.githubusercontent.com/38428845/160309246-ddf749d4-fd16-4a16-a5b8-40e706620cbf.png">
@dexios1 this is fixed

**Comment by chris-dare** [comment]
Thank you very much
