### ISSUE TITLE
feature/suspend a corporate payer's benefactor (employee)

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#23]
**Tell us about your request!**
We should be able to suspend a payer's benefactor in the app. First, this will be in on the EMR and then exclusively on the corporate portal

**Which app does this concern?**
Provider portal

**What will be benefit of this feature?**
When suspended benefactors are billed, this leads to claim disputes and revenue loss for providers. Suspending these benefactors ensure that revenue is not missed.

**Describe the solution you'd like**
Implement a feature to suspend employees. 
Effort score: 3 (design, FE, and BE)

This should suspend the benefactor's record and their account
When retrieving a patient's payment method, this account should also not be available for use

When paying for a charge item, payment should not be processed if the account is suspended.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chris-dare** [comment]
Notes from call with Kwasi:

*Employee suspension*
- Some organizations update their list of employees by sending their blacklist
- Other organizations update their list of employees by sending their active employees

So it's important to ensure that we have processes for both use cases implemented.

*Employee dependent suspension*
HIS currently adds dependent beneficiaries as patients.

Also important to identify employees and beneficiaries that we suspended. If they used the company after the date of suspension, those patients will need to cover the cost of that bill

**Comment by pkdadson** [comment]
@dexios1 please I don't understand this request.

**Comment by chris-dare** [comment]
Hi @pkdadson,

I've just tried out the feature. It works but it doesn't return the status of activity for the employee which is what you need.

@TuyizereBapt, please expose the `is_active` flag in both the `LegacyEmployeeSerializer` and `InsuranceBeneficiarySerializer` so that they are returned in the API response

@pkdadson, also please send the action in uppercase instead. We implemented it UPPERCASE unfortunately so I need you to update that on the frontend please. i.e. 
```JSON
{
  "action": "SUSPEND"
}
```

**Comment by pkdadson** [comment]
Please update the api docs on that too

**Comment by chris-dare** [comment]
Done

**Comment by chris-dare** [comment]
@pkdadson  the flag status now needs to be displayed so that the users can tell if an employee is active or not

**Comment by TuyizereBapt** [comment]
Working on it now

**Comment by pkdadson** [comment]
@dexios1 will show the status on the table
but can we active the user again?

**Comment by chris-dare** [comment]
> @dexios1 will show the status on the table but can we active the user again?

- Yes. please show the status on the table
- Yes we should be able however we'll have to address this in a separate PR. @TuyizereBapt can you create a card and work on this too? i.e. reactivate an employee

**Comment by chris-dare** [comment]
Hi @pkdadson, the employees now have the `is_active` flag exposed.

Thanks for completing this @TuyizereBapt

**Comment by TuyizereBapt** [comment]
> > @dexios1 will show the status on the table but can we active the user again?
> 
> * Yes. please show the status on the table
> * Yes we should be able however we'll have to address this in a separate PR. @TuyizereBapt can you create a card and work on this too? i.e. reactivate an employee

What should be the data from the front-end to pinpoint the employee to be reactivated? @dexios1 @pkdadson

**Comment by chris-dare** [comment]
@TuyizereBapt Let's use the action `ACTIVATE`

**Comment by TuyizereBapt** [comment]
> @TuyizereBapt Let's use the action `ACTIVATE`

I mean something unique to identify the employee. can I expect the `Employee.id`?

And in addition, if the endpoint's sole purpose is updating the `Employee.is_active` why use the the action **ACTIVATE**?

**Comment by chris-dare** [comment]
> > @TuyizereBapt Let's use the action `ACTIVATE`
> 
> I mean something unique to identify the employee. can I expect the `Employee.id`?
> 
> And in addition, if the endpoint's sole purpose is updating the `Employee.is_active` why use the the action **ACTIVATE**?

Hey, thanks for this. It's going to be an extension of the Benefactor action API view. So you just need to support the activation process in `Employee.process_action`. See #97 for additional clarity

**Comment by pkdadson** [comment]
@dexios1 @TuyizereBapt  so what will be the key **status / is_active**?

**Comment by TuyizereBapt** [comment]
> @dexios1 @TuyizereBapt so what will be the key **status / is_active**?

The key is `is_active`

**Comment by chris-dare** [comment]
@pkdadson please let me know when this integration is updated on the frontend

**Comment by pkdadson** [comment]
@TuyizereBapt Please the value of is_active is a boolean instead of the value of the action. Or @dexios1

**Comment by chris-dare** [comment]
> @TuyizereBapt Please the value of is_active is a boolean instead of the value of the action.

Yes please. It's the structure from the v0.5 implementation. Ehi recommended that we maintain it and I think this is fine for the employee. Will this be a challenge? We can make an improvement for an easier integration.

**Comment by pkdadson** [comment]
Alright, it's fine. done and merged @dexios1 @TuyizereBapt

**Comment by chris-dare** [comment]
Thank you @pkdadson! Please let me know when it's up on the app

**Comment by pkdadson** [comment]
It's on the app @dexios1

**Comment by chris-dare** [comment]
Thank you checking it out!

**Comment by chris-dare** [comment]
Hi @pkdadson, thanks for completing this. The integrations work as intended! Thank you!

@TuyizereBapt unfortunately, I was still able to access the payment method of a suspended employee. Please try this out in the app. Here's what you need to do:
1. Add yourself as an employee to one of the corporate clients we have set up
2. Suspend your self from that company
3. Start a visit and attempt to pay via that company (this should not be possible)
Please take a look at it when you are available. Have a good evening.

Well done guys. I'm very happy we've been able to pull this off.

**Comment by TuyizereBapt** [comment]
> When retrieving a patient's payment method, this account should also not be available for use
> 
> When paying for a charge item, payment should not be processed if the account is suspended.

OOh I see the problem. I think when I implemented this, I forgot to work on the other points:
     2. When retrieving a patient's payment method, this account should also not be available for use
     3. When paying for a charge item, payment should not be processed if the account is suspended.
   
I don't know what happened that I didn't read it all. I will fix it

**Comment by chris-dare** [comment]
Ok great. Thanks and looking forward to it!

**Comment by pkdadson** [comment]
@TuyizereBapt please any feedback on this task?

**Comment by TuyizereBapt** [comment]
I think I fixed the bug. You can try it and see if it works on your end

**Comment by chris-dare** [comment]
Hey guys, let's set up a different card for suspending beneficiaries for insurance
