### ISSUE TITLE
feature/download patient diagnostic report from patient's profile in OPD workspace

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#24]
**Tell us about your request!**
Doctors would like to view a pdf of diagnostic reports from a patient's profile within the OPD workspace

**Which app does this concern?**
Provider portal? Corporate portal? Patient app?

**What will be benefit of this feature?**
What's the value of this feature? If you can quantity it, that would be awesome!

**Describe the solution you'd like**
Make the button to download documents available within the OPD workspace
![image](https://user-images.githubusercontent.com/18426797/148258347-b5776a01-2448-41d9-b97c-1e6a12aeba0c.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pkdadson** [comment]
@dexios1 please that button is already in the OPD workspace<img width="1439" alt="Screenshot 2022-01-10 at 00 00 46" src="https://user-images.githubusercontent.com/38428845/148706532-cb9171a6-c26e-4725-b9b0-5ac51b21fe20.png">

**Comment by chris-dare** [comment]
Hi @pkdadson thanks for this. I'll try to make the asks more specific going forward. It should be easier now especially with Richmond resuming his operations. 

The doctors need to see it on the patient's profile. Currently they do not have that button on their profile. See the image below:  
![image](https://user-images.githubusercontent.com/18426797/148906009-51127c50-863d-49d6-8ec4-3310f339ccfe.png)
