### ISSUE TITLE
bugfix/check service request status

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#25]
**Describe the bug**
CEs working with the diagnostics team are unable to view in realtime, status of service requests

**Impact**
If the CEs don't find the patient's service request or see the status, then patient reports will be delayed.

**To Reproduce**
1. Go to Reception workspace
2. Click on diagnostic orders in the sidebar
3. Search for a completed service request
4. You'll notice that you can't one has a status of completed and you also can't see the lab ids

**Expected behavior**
CEs should be able to see requests and be able to determine the following from the list of service requests:
1. Status (include the payment status)
2. Lab ids (these are used to identify the collected specimen for each service request)
3. Search is made by biomedical scientists on statuses of samples and communicated to CEs

**Screenshots/Screencast**
N/A

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser: Chrome
 - Version: Unknown

**Additional context**
N/A

**Comment by chris-dare** [comment]
Statuses should also be user friendly.

Also, notes (order details) from the service request should be present when a service request is viewed

cc: @pkdadson

**Comment by dexios1** [comment]
Fixed in https://github.com/serenity-health/core-systems-api/pull/3
