### ISSUE TITLE
feature/display reference ranges for lab reports

### ISSUE THREAD

**Issue by dexios1** [serenity-health/roadmap#3]
**Tell us about your request!**
Doctors need to see references ranges on lab reports where applicable and the information is available to be displayed

**Which app does this concern?**
Provider portal

**Describe the solution you'd like**
When view a report, we should see the observations, unit of measurement, reference ranges and an interpretation as seen in the image below. This should be displayed iff the diagnostic test has been configured with that information (i.e. unit of measurement and reference ranges)
![image](https://user-images.githubusercontent.com/18426797/147815909-5df7b41f-79aa-4250-96e1-d3058643564a.png)

Source: https://www.hl7.org/fhir/diagnosticreport-example.html

**Describe alternatives you've considered**
Doctors can have a standalone sheet of reference ranges to compare with test results. However, that's not the best

**Additional context**
N/A

**Comment by dexios1** [comment]
Part of this also includes sourcing the data. Richmond (locum consultant) will be working with us to provide the necessary info

**Comment by pkdadson** [comment]
Please @dexios1 are you done taking Richmond through?

**Comment by chris-dare** [comment]
Hi @pkdadson, I've taken him through however he's yet to complete it. Once it's done, we should be able to close of this issue. 
In the meantime, I'm working with the data we have already received to ensure that the reference ranges are exposed in the API for you to display. You shouldn't have much to do because we have already integrated this into the app but a 2nd look is definitely necessary.

**Comment by pkdadson** [comment]
@dexios1  <img width="758" alt="Screenshot 2022-01-12 at 04 29 13" src="https://user-images.githubusercontent.com/38428845/149063992-f7e2ff61-6fee-44b3-816f-84bd7dcb4233.png">

**Comment by chris-dare** [comment]
Noted.

Hey btw I noticed the units from the observation unit category valueset are not being sent back to the API

![image](https://user-images.githubusercontent.com/18426797/149470651-b894447c-02c9-4e47-ad11-613e9e3e4bef.png)


Try entering results for a complete blood count to see what I mean

**Comment by chris-dare** [comment]
Closed in core systems - 5
