### ISSUE TITLE
feature/add dosage form to medication request

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#33]
**Tell us about your request!**
Dosage forms need to be saved and displayed on medication requests in the OPD and Pharmacy workspace

**Which app does this concern?**
Provider portal

**What will be benefit of this feature?**
Pharmacists will know what kind of medications to be dispensed. It willl prevent cancelation of bills and ensure that the patients receive the right drugs

**Describe the solution you'd like**
Expose the medication dosage form input on:
1. Medication Request
2. Inventory

When dispensing drugs, display medication dosage form of:
1. Medication request
2. Inventory item

**Describe alternatives you've considered**
Medications or offline communication used. Subject to error

**Additional context**
N/A

**Comment by seddie62** [comment]
@dexios1 is there a design for this

**Comment by chris-dare** [comment]
Alas, no.

It will be similar to the other fields though (e.g. the medication name).
So we're looking at a dropdown for the input
And a text display for the output.

Tryna get Richmond back this week to help with the visuals

**Comment by seddie62** [comment]
Anything on this @dexios1

**Comment by chris-dare** [comment]
Unfortunately not. Will discuss with @TuyizereBapt

**Comment by TuyizereBapt** [comment]
Need help with this issue @dexios1

**Comment by chris-dare** [comment]
Noted.

**Comment by chris-dare** [comment]
Hi @TuyizereBapt 

Medications have dosage forms which basically indication what form of input the drug should be taken in.

Let's take paracetamol for example. It can be a tablet, a syrup or an oral suspension.

The doctors want to state the dosage form of the drugs they prescribe to patients so that a pharmacist can dispense the right medication to the patient. To accomplish this, we will need to extend the medication request model with a field for dosage form.

This has already been done for the Stock model in the pharmacy app and so you resuse that text choice of dosage forms.

**Comment by TuyizereBapt** [comment]
> Hi @TuyizereBapt
> 
> Medications have dosage forms which basically indication what form of input the drug should be taken in.
> 
> Let's take paracetamol for example. It can be a tablet, a syrup or an oral suspension.
> 
> The doctors want to state the dosage form of the drugs they prescribe to patients so that a pharmacist can dispense the right medication to the patient. To accomplish this, we will need to extend the medication request model with a field for dosage form.
> 
> This has already been done for the Stock model in the pharmacy app and so you resuse that text choice of dosage forms.

Done

**Comment by chris-dare** [comment]
API implementation complete.
@seddie62 this is available for integration. We'd like to see this in the:
1. Encounter wizard
2. Prescription view on the patient profile
3. Prescription view when the pharmacist is filling prescriptions
4.

**Comment by chris-dare** [comment]
Thanks for completing this @TuyizereBapt

**Comment by chris-dare** [comment]
@seddie62 what's the progress on this?

**Comment by seddie62** [comment]
@TuyizereBapt What's the field name and the API to get the doses?

**Comment by TuyizereBapt** [comment]
> @TuyizereBapt What's the field name and the API to get the doses?

dosage_form

**Comment by TuyizereBapt** [comment]
> > @TuyizereBapt What's the field name and the API to get the doses?
> 
> dosage_form

I did not create a new API endpoint for it. It's just the same endpoints for MedicationRequest

**Comment by chris-dare** [comment]
Hi @seddie62,

I'm just realizing we hadn't exposed the valueset. Give me 20 minutes and I'll set it up for you

**Comment by chris-dare** [comment]
@seddie62 done at `{{base_url}}/providers/valueset/dosage-form-type`
