### ISSUE TITLE
feature/display patient payment methods on profile [pharmacy]

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#39]
**Tell us about your request!**
Display known payment methods on patient profile when dispensing medications

**Which app does this concern?**
Provider portal

**What will be benefit of this feature?**
What's the value of this feature? If you can quantity it, that would be awesome!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chris-dare** [comment]
@seddie62 I've noticed that I'm able to see this for corporates but not for insurance payment methods. You may need to double check to be sure.

**Comment by chris-dare** [comment]
@seddie62 @pkdadson do check this out. No API update is required

**Comment by seddie62** [comment]
@dexios1 I don't have permissions to assign dadson. @pkdadson can you take over this task? I'm a little lost

**Comment by chris-dare** [comment]
@seddie62 thanks for this. I've assigned this to Dadson.

Here is the issue. 

Consider the fictional insurance provider "Fred insurance company". It has an active beneficiary "Apextest Insurancetest"

![image](https://user-images.githubusercontent.com/18426797/155277602-57de4aa4-11df-463e-bd67-9c0392ffc917.png)

Checkout "Apextest Insurancetest"'s [patient profile in the pharmacy workspace](https://demo.provider.serenity.health/pharmacy/patients/13/?type=existing). You'll see that although they have 2 insurance payment options, none of those show up as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/18426797/155278542-efb2900a-db02-4d0e-b0ba-a5f8f6b49042.png)

The pharmacists want to see the payment options the patient has so they can make a decision on which drugs to dispense to a patient. (Context: Some insurance providers will not settle claims to certain medications dispensed based on the patient's insurance policy)

**Comment by pkdadson** [comment]
Okay @dexios1 but are the drugs dependent on the payment methods?

**Comment by pkdadson** [comment]
And I want to know if there will be actions on those methods?
 @dexios1

**Comment by chris-dare** [comment]
> Okay @dexios1 but are the drugs dependent on the payment methods?

Sometimes. See https://www.priorauthtraining.org/what-is-an-insurance-exclusion-list/

**Comment by chris-dare** [comment]
> And I want to know if there will be actions on those methods? @dexios1

Not for this release.
In a future release, we may need to show the exclusion list for each payment method the patient has access to.
