### ISSUE TITLE
feature/display dispensed medications

### ISSUE THREAD

**Issue by dexios1** [serenity-health/roadmap#7]
**Tell us about your request!**
Pharmacists would like to see medications dispensed within a patient's profile in addition to medication prescribed

**Which app does this concern?**
Provider portal

**Describe the solution you'd like**
In the pharmacy workspace we should view a list of medications dispensed for a patient. Each dispensed medications should contain:
1. Name of drug
2. Dosage amount
3. Dosage form
4. Dosage unit
5. Quantity dispensed
6. Dispensed by (Practitioner)

**Describe alternatives you've considered**
View the patient's bill. It doesn't display information like the dosage details though

**Additional context**
N/A

**Comment by chris-dare** [comment]
Note: Inventory items currently do not store dosage form. We'll need to account for this

**Comment by chris-dare** [comment]
We have made the prescription feature available in the pharmacy workspace which allows us to view all prescriptions made for a patient (dispensed or not)
