### ISSUE TITLE
bugfix/all doctors are displayed as GP

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#78]
**Describe the bug**
All doctors and specialists are tagged as GPs. We have an outcry from specialists in this regard because of the implications
![image](https://user-images.githubusercontent.com/18426797/152729576-3dde6195-ca93-425d-9197-02a50c43c088.png)

**Impact**
Specialists may get the impression that they may be billed wrongly

**To Reproduce**
1. Go to reception workspace
2. Start a visit for an Obs and Gyne consultation with an Obs and Gyne doctor
3. Switch to OPD workspace
4. View the patient's profile and you'll see that the doctor has been tagged as a GP

**Expected behavior**
Doctors should be labelled as "practitioners" and not General practitioners. (We can consider displaying their actual specialties somewhere done the line but now is not the time)

**Comment by seddie62** [comment]
@dexios1 there's no speciality provided by the api for this


<img width="534" alt="Screenshot 2022-02-14 at 7 11 28 AM" src="https://user-images.githubusercontent.com/32453214/153816822-3a539afd-d0fa-435c-8ce4-a3c938788acf.png">


<img width="517" alt="Screenshot 2022-02-14 at 7 11 20 AM" src="https://user-images.githubusercontent.com/32453214/153816842-6b9745c3-95a3-48b7-9120-b194e3226563.png">

**Comment by chris-dare** [comment]
@seddie62 Yes just display "Practitioner" biko

**Comment by seddie62** [comment]
this is done oo. Or? @dexios1

**Comment by chris-dare** [comment]
That's correct.


Kind regards,
Chris Dare

E: ***@***.******@***.***>
P: +233 26 226 0986 / +250 786 745 117<tel:+233%2026%20226%200986%20/%20+250%20786%20745%20117>
W: http://chrisdare.me<http://chrisdare.me/>
[LinkedIn]<https://linkedin.com/in/csdare/>[Twitter]<https://twitter.com/chrisdare_>
