### ISSUE TITLE
feature/edit an insurance patient'scoverage

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#79]
**Tell us about your request!**
CEEs would like to edit a patient's insurance coverage

**Which app does this concern?**
Provider portal

**What will be benefit of this feature?**
Mistakes can be corrected. In the absence of an insurance API integration, the patient's coverage can be edited

**Describe the solution you'd like**
Implement an API to edit the coverage of an `organization.models.Employee` iff the managing organization is an insurance provider. See API spec [here](https://serenity-health.readme.io/reference/insurance-clients-and-payments#edit-an-insurance-beneficiary).
 
**Describe alternatives you've considered**
This has currently been edited manually for a while now and needs to end

**Additional context**
N/A

**Comment by chris-dare** [comment]
@agbavorrichmond I need you to design a screen for @pkdadson to implement this on the frontend. Let's discuss after this morning's call

**Comment by TuyizereBapt** [comment]
@dexios1  I did not  find any use of the parameters in the URL in the API spec [here](https://serenity-health.readme.io/reference/insurance-clients-and-payments#edit-an-insurance-beneficiary)

**Comment by chris-dare** [comment]
Hi @pkdadson an API is ready for this. @TuyizereBapt is available to support you on the integration

**Comment by chris-dare** [comment]
Hi @pkdadson,

Editing a corporate employee yields a 404 since it's a different endpoint.

@seddie62 I'm not sure the caching works well with retrieving policies. I think that if it fails, it may not attempt to retrieve the policies again. I've noticed that the policies component fails to retrieve policy data at times.

**Comment by chris-dare** [comment]
Note: Updated the title to match the description
