### ISSUE TITLE
feature/display patient billing history on their profile

### ISSUE THREAD

**Issue by dexios1** [serenity-health/roadmap#8]
**Tell us about your request!**
We'd like to view a patient's billing history on their profile. This is just like you'd see the bills menu of the billing workspace but filtered by one patient

**Which app does this concern?**
Provider portal?

**Describe the solution you'd like**
Add a new tab for billing history and display the patient's bills. Here's how it should look like:
Tabular data information:
1. Date of bill creation
2. Bill id (charge item user friendly id)
3. Service of product name
4. Total charge
5. Payment status
6. Actions

Filters:
1. Date range for bill creation (i.e. from and to)
2. Category (use service category valueset)
3. Payment method

**Describe alternatives you've considered**
We can use a metabase report as an interim solution

**Additional context**
N/A

**Comment by chris-dare** [comment]
By implementing this issue we may not have to work on #7

**Comment by chris-dare** [comment]
Hi @pkdadson, I see we have this in the billing workspace: https://demo.provider.serenity.health/billing/patients/14/bills
So we'll just have to make it available in the OPD and reception workspaces. 
Finally, the missing filters and columns would have to be functional and visible.

**Comment by chris-dare** [comment]
Hi @pkdadson, thanks for speaking. I just checked and can confirm that the filters are currently present. Here are the filter fields you need:

1. `category` (use the HealthcareServiceCategoryType valueset for this)
2. `created_on__after`
3. `created_on__before` 

So if I wanted to find Consultation bills from the 1st of Jan to 21st of december, these will be my filter values:
```json
{
    'created_on__after': '2022-01-01 00:00', 
    'created_on__before': '2022-12-31 10:00',
    'category': 'CONSULTATION'
}
```

**Comment by chris-dare** [comment]
Hey @pkdadson,

Thanks for working on this. It's great to see this!

I'm sharing initial feedback on areas that need improvement. 
I'm not able to select a service category. Please use the healthcare service category valueset for this.

![image](https://user-images.githubusercontent.com/18426797/148755287-43e4f4d8-3a29-4d82-82ab-8aa526c75ed2.png)

I also notice that, after changing the date range the 2nd time, it does not make an API call.
