### ISSUE TITLE
bugfix/healthcare service unique constraint migration

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#82]
**Describe the bug**
Healthcare services data on production and demo need to be cleaned to enable a pending migration. This migration sets a unique together constraint for the following fields on the Healthcare service model:
1. provider id
2. order code

**Impact**
Difficult to keep track of migrations and work on new features. This is piling up dangerous technical debt and makes it harder for make improvements to the code + build new features

**To Reproduce**
1. Make a migration on the `patients` or `fhirresourcemanager` apps
2. You'll notice that in the new migration files for fhirresourcemanager, there's a unique together constraint created for `Healthcareservice` for the fields `(provider, order_code)`
3. Run that migration
4. You'll notice that the constraint cannot be effected on the database because there are duplicates for that combination

**Expected behavior**
Migration should run effectively without fail

**Comment by TuyizereBapt** [comment]
I removed the contraint yesterday while implementing revenue tags
