### ISSUE TITLE
bugfix/disappearing encounter notes

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#85]
**Describe the bug**
Doctors report that they cannot find some notes typed in during previous patient visits

**Impact**
Context concerning patient's condition is lost leading to inadequate provision of care

**To Reproduce**
- Not sure. Will need to investigate
 
**Expected behavior**
All previous encounter notes should be visible

**Screenshots/Screencast**
N/A

**Additional context**
N/A

**Comment by chris-dare** [comment]
Hi @TuyizereBapt @seddie62,

Just resharing the slack conversations here so @DanielDarko12 can get some visibility on the progress and efforts being taken to resolve this

**Comment by chris-dare** [comment]
@DanielDarko12 we reproduced the issue you mentioned on missing notes. 

Here's is an example from a dummy patient profile we set up for @TuyizereBapt. 
We went through a patient walkthrough and created a consultation for the patient on the 25th of January however we are unable to see the notes from that encounter on the patient profile:

![image](https://user-images.githubusercontent.com/18426797/154731109-90c83c16-35b9-4824-885f-c69f48d6f31c.png)

The bill for that encounter show up:
![image](https://user-images.githubusercontent.com/18426797/154731552-87292fce-5c14-4364-bfaf-73500a490854.png)

And we can also view the notes in the database. @TuyizereBapt is working with @seddie62 to resolving this issue. We will notify you and your team when it's done.


Live demo: https://demo.provider.serenity.health/patients/14496/encounters

**Comment by chris-dare** [comment]
@TuyizereBapt, here's what I found from running a check. It doesn't have to do with what's on production though but with the new link patients feature. So it may not necessary have to do with what the doctors are facing now. See the image below.
I think it's related to viewing the profiles of patients without patient links:

I inserted some breakpoint in `EncounterListView`
![image](https://user-images.githubusercontent.com/18426797/154737203-17c1bb2f-494a-4cd6-83b7-0a64833b8f44.png)

And here's what I observed:
![image](https://user-images.githubusercontent.com/18426797/154737002-110b1d2d-8622-48df-acf7-59e604a71d81.png)

**Comment by chris-dare** [comment]
Updates on this issue: https://github.com/serenity-health/roadmap/discussions/108

We're down to updating FK restrictions and an audit log for deleting notes.

**Comment by DanielDarko12** [comment]
Happy to hear this is closed

Daniel Osafo Darko , MD, MGCPS(Fam Med)Specialist Family Physician+233 50 644 32 74http://www.linkedin.com/in/daniel-osafo-darko-592baa87
 "Let your life reflect the faith you have in God. Fear nothing and pray about everything. Be strong, trust God’s word, and trust the process." - Germany Kent

 

    On Tuesday, March 15, 2022, 07:51:22 AM GMT, Chris Dare ***@***.***> wrote:  
 
 


Closed #85.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
