### ISSUE TITLE
feature/set patient last mode of payment as default payment method on checkout/payment

### ISSUE THREAD

**Issue by chris-dare** [serenity-health/roadmap#89]
**Tell us about your request!**
It would be helpful to display the last mode of payment that the patient used when checking out a bill payment.
So if I paid via Clearspace on my last visit, the default category should be corporate with Clearspace selected by default. When checking out. If I changed the payment method, then that now becomes my last used payment method

**Which app does this concern?**
Provider portal

**What will be benefit of this feature?**
What's the value of this feature? If you can quantity it, that would be awesome!

**Describe the solution you'd like**
1. On the backend, update the patient profile to store:
a. The last payment method used
b. The account uuid of the account used to pay (if cash, then this will be set to None)
Expose this in retrieving the details of a patient on GET
2. On the frontend, implement the feature based on the API update

**Describe alternatives you've considered**
N/A

**Additional context**
#38 
#63

**Comment by chris-dare** [comment]
Hi @TuyizereBapt, here's what you need to do on the API side of things:

1. Extend the `Patient` model to save the following fields:
a. `previous_payment_method`: Textchoice based on `base.choices.PaymentMethodType`
b. `previous_patient_account_uuid` (UUIDField)

2.  In ChargeItem.settle_payment, once the account is used to settle the payment, set the patient previous payment method and account to the charge item's payment method and patient account (if a patient account was used)

3. Document `PatientAccount.pay_for_charge_items()` -> This is for @dexios1 to do

4. Update `PatientAccount.pay_for_charge_items()` such that it sets charge_item.patient_account and charge_item.payer_account after a payment for a charge item is successful

**Comment by dexios1** [comment]
@seddie62 this is up for integration. 

Look out for these new fields:

`previous_payment_method` (will be empty or one of the payment method types: cash, corporate, user account or insurance)
`previous_patient_account_uuid` = will be empty if the `previous_payment_method` is null or cash

**Comment by chris-dare** [comment]
@pkdadson this is up for integration. 

Look out for these new fields:

`previous_payment_method` (will be empty or one of the payment method types: cash, corporate, user account or insurance)
`previous_patient_account_uuid` = will be empty if the `previous_payment_method` is null or cash

**Comment by chris-dare** [comment]
@pkdadson please let me know when it's integrated on the frontend

**Comment by chris-dare** [comment]
Notes from review:

API is setting the details but needs to be done on the frontend as well.

Here's what we're getting:
Nothing selected by default
![image](https://user-images.githubusercontent.com/18426797/155499543-0c1edc18-f817-4245-9484-3c9efa5d5bf4.png)

Here's what we should be doing instead:
Previous payment method selected by default:
![image](https://user-images.githubusercontent.com/18426797/155499624-f12714ea-9e6d-4ed8-bb9f-a512d16a1c46.png)

**Comment by pkdadson** [comment]
done @dexios1
