### ISSUE TITLE
feature/reactivate an employee

### ISSUE THREAD

**Issue by TuyizereBapt** [serenity-health/roadmap#97]
**Tell us about your request!**
A corporate administrator may want to reactivate a suspended employee. We should make this possible in the EMR until the corporate portal goes live

**Which app does this concern?**
Provider portal

**What will be benefit of this feature?**
Patients eligible to corporate coverage will be able to pay with their company

**Describe the solution you'd like**
Extend `Employee.process_action` to support activation
This should reverse the suspension process i.e:
1. Set the `is_active` field to True
2. Activate the related patient accounts that were suspended
NB: You will need to support `PatientUserAccountActionType` to support the `ACTIVATED` action and have it logged in the action history

**Describe alternatives you've considered**
N/A

**Additional context**
See #23

**Comment by chris-dare** [comment]
Thanks for creating this @TuyizereBapt. I have updated the description to make it clearer

**Comment by TuyizereBapt** [comment]
Done

**Comment by chris-dare** [comment]
Hi @pkdadson, there's a new API to activate employees: https://serenity-health.readme.io/reference/accounts#activate-a-benefactor

**Comment by chris-dare** [comment]
@pkdadson please let me know when this is integrated on the frontend

**Comment by chris-dare** [comment]
Just realized we still have this open. Closing it
